package Models;

public class ClothingStock {
    private int stockId;
    private String clothId;
    private String color;
    private String size;
    private int quantity;

    public ClothingStock() {}

    // Full Constructor (Used when retrieving data from DB)
    public ClothingStock(int stockId, String clothId, String color, String size, int quantity) {
        this.stockId = stockId;
        this.clothId = clothId;
        this.color = color;
        this.size = size;
        this.quantity = quantity;
    }

    // Constructor for adding/restocking (StockId is generated by DB)
    public ClothingStock(String clothId, String color, String size, int quantity) {
        this.clothId = clothId;
        this.color = color;
        this.size = size;
        this.quantity = quantity;
    }

    // Getters and Setters
    public int getStockId() { return stockId; }
    public void setStockId(int stockId) { this.stockId = stockId; }

    public String getClothId() { return clothId; }
    public void setClothId(String clothId) { this.clothId = clothId; }

    // ⭐ NEW Getter/Setter for Color
    public String getColor() { return color; }
    public void setColor(String color) { this.color = color; }

    public String getSize() { return size; }
    public void setSize(String size) { this.size = size; }

    public int getQuantity() { return quantity; }
    public void setQuantity(int quantity) { this.quantity = quantity; }
}